import { FlatCompat } from "@eslint/eslintrc";
import jsxA11y from "eslint-plugin-jsx-a11y";

const compat = new FlatCompat({
  baseDirectory: import.meta.dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  // jsx-a11y "strict" catches accessibility problems at lint time,
  // before they ever reach a browser or a test run. The plugin itself
  // is already registered by next/core-web-vitals, so only the rules
  // are added here — redefining the plugin is an error in ESLint 9.
  { rules: jsxA11y.flatConfigs.strict.rules },
  {
    ignores: [
      ".next/**",
      "out/**",
      "coverage/**",
      "node_modules/**",
      // Generated by Next.js; not ours to lint.
      "next-env.d.ts",
    ],
  },
];

export default eslintConfig;
